apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddms.fullname" . }}-backend-config
  labels:
    {{- include "ddms.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.nodeEnv | quote }}
  PORT: {{ printf "%d" .Values.backend.env.port | quote }}
  ALLOWED_ORIGINS: {{ join "," .Values.backend.env.allowedOrigins | quote }}
