apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddms.fullname" . }}-frontend
  labels:
    {{- include "ddms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/component: frontend
    {{- include "ddms.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
