{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ddms.fullname" . }}
  labels:
    {{- include "ddms.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.frontendHost }}
      secretName: {{ include "ddms.fullname" . }}-frontend-tls
    - hosts:
        - {{ .Values.ingress.apiHost }}
      secretName: {{ include "ddms.fullname" . }}-api-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ddms.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ddms.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
